# Config version. Do not change this
config-version = "2.6"
bind = "0.0.0.0:25565"
# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Only MiniMessage format is accepted.
motd = "Welcome to MC Frens!"
show-max-players = 25
online-mode = true
force-key-authentication = false
prevent-client-proxy-connections = false
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"
enable-player-address-logging = true

[servers]
	#world2 = "127.0.0.1:30067"
	lobby = "127.0.0.1:30008"
	#moddedsurvival="127.0.0.1:30880"
	# In what order we should try servers when a player logs in or is kicked from a server.
	try = ["lobby", "world1"]
	world1 = "127.0.0.1:30066"

[forced-hosts]
	"world1.mcfrens.com" = ["world1"]
	# Configure your forced hosts here.
	"lobby.mcfrens.com" = ["lobby"]

[advanced]
	read-timeout = 30000
	tcp-fast-open = false
	compression-level = -1
	compression-threshold = 256
	login-ratelimit = 3000
	connection-timeout = 5000
	log-player-connections = true
	bungee-plugin-message-channel = true
	show-ping-requests = false
	failover-on-unexpected-server-disconnect = true
	announce-proxy-commands = true
	haproxy-protocol = false
	log-command-executions = false

[query]
	port = 25565
	show-plugins = false
	map = "MC Frens"
	enabled = false

